import pandas as pd


'''Questions

Total number of customers: Count the unique customer IDs.
Number of customers in each city: Group by CITY and count, sorted by city name.
Number of customers in each country: Group by COUNTRY and count, sorted by country name.
Country with the most contracts: Find the country with the highest sum of CONTRCNT (contract count).
Unique cities with at least one customer: Count distinct city names.

'''


# my code
# Function to generate output strings
def generate_string(records, title, key_field, value_field):
    res = f"{title}:\n"
    for record in records:
        res += f"{record[key_field]}: {record[value_field]}\n"
    return res

def analyze_data2(csv_path):
    df = pd.read_csv(csv_path)
    
    # Total unique customers
    unique_customers = df["ID"].nunique()
    
    # Customers count by city and by country
    customer_count_by_city = df.groupby("CITY").agg(city_count = ("ID", "count")).reset_index()
    customer_count_by_country = df.groupby("COUNTRY").agg(country_count = ("ID", "count")).reset_index()
    
    # Sorting for city and country counts
    customer_count_by_city = customer_count_by_city.sort_values(by="CITY")
    customer_count_by_country = customer_count_by_country.sort_values(by="COUNTRY")
    
    # City and country dictionaries for easier string generation
    customer_count_by_city_dict = customer_count_by_city.to_dict("records")
    customer_count_by_country_dict = customer_count_by_country.to_dict("records")
    
    # Find the country with the largest number of contracts
    country_contracts = df.groupby('COUNTRY')['CONTRCNT'].sum()
    max_country = country_contracts.idxmax()
    max_contracts = country_contracts.max()
    
    # Unique cities with at least one customer
    unique_city_count = df["CITY"].nunique()
    
    # Generate strings for each section
    unique_city_string = f"Unique cities with at least one customer: {unique_city_count}\n"
    total_customer_string = f"Total customers: {unique_customers}\n"
    customer_by_city_string = generate_string(customer_count_by_city_dict, "Customers by city", "CITY", "city_count")
    customer_by_country_string = generate_string(customer_count_by_country_dict, "Customers by country", "COUNTRY", "country_count")
    contract_string = f"Country with the largest number of customers' contracts: {largest_contract_country['COUNTRY']} ({int(largest_contract_country['contract_sum'])} contracts)\n"
    
    # Combine all strings into the final output
    final_string = total_customer_string + customer_by_city_string + customer_by_country_string + contract_string + unique_city_string
    print(final_string)

# Call the function with the CSV path
# analyze_data("/root/customers/data.csv")



import pandas as pd
# Code generated by chat gpt

def analyze_data(csv_path):
    # Read CSV data
    df = pd.read_csv(csv_path)
    
    # 1. Total number of unique customers
    total_customers = df["NAME"].nunique()
    
    # 2. Number of customers in each city (sorted by city name)
    customer_count_by_city = df.groupby("CITY").agg(customer_count=("ID", "count")).reset_index()
    customer_count_by_city = customer_count_by_city.sort_values(by="CITY")
    
    # 3. Number of customers in each country (sorted by country name)
    customer_count_by_country = df.groupby("COUNTRY").agg(customer_count=("ID", "count")).reset_index()
    customer_count_by_country = customer_count_by_country.sort_values(by="COUNTRY")
    
    # 4. Country with the largest number of customers' contracts
    #    Sum up the contract count and find the country with the highest total
    contract_count_by_country = df.groupby("COUNTRY").agg(total_contracts=("CONTRCNT", "sum")).reset_index()
    contract_count_by_country = contract_count_by_country.sort_values(by=["total_contracts", "COUNTRY"], ascending=[False, True])
    top_contract_country = contract_count_by_country.iloc[0]
    
    # 5. Number of unique cities with at least one customer
    unique_city_count = df["CITY"].nunique()
    
    # Formatting the output as a single string
    output = []
    output.append(f"Total customers: {total_customers}")
    output.append("Customers by city:")
    for _, row in customer_count_by_city.iterrows():
        output.append(f"{row['CITY']}: {row['customer_count']}")
    output.append("Customers by country:")
    for _, row in customer_count_by_country.iterrows():
        output.append(f"{row['COUNTRY']}: {row['customer_count']}")
    output.append(f"Country with the largest number of customers' contracts: {top_contract_country['COUNTRY']} ({int(top_contract_country['total_contracts'])} contracts)")
    output.append(f"Unique cities with at least one customer: {unique_city_count}")
    
    # Join the list into a single output string
    final_output = "\n".join(output)
    print(final_output)

# Path to the CSV file
csv_path = r"C:\development\repo\python_for_beginners\pandas\hrt_data.csv"
analyze_data2(csv_path)
